### ISSUE TITLE
Страница пустой корзины

### ISSUE THREAD

**Issue by evgeniysolodkov** [springhead-su/legko.marketing#13]
- [x] Решить, нужна ли страница с текстом, что корзина пуста или отключать переход и делать редирект при прямом обращении к пустой корзине
- [x] Контент для пустой корзины (если будет)
- [x] Прототип
- [x] Дизайн
- [x] Верстка

**Comment by marymal** [comment]
Может пустая корзина будет просто неактивна? Че на нее жать вообще?
А вот если удалишь все товары, находясь в корзине, то выводить сообщение, как сейчас «Корзина пуста»
