### ISSUE TITLE
Тестирование админки

### ISSUE THREAD

**Issue by evgeniysolodkov** [springhead-su/legko.marketing#18]
**Категории**

- [x] при создании товара и его сохранении не исчезает кнопка «обновить», а товар дублируется при повторном нажатии «сохранить»
- [x] нельзя использовать одинаковые слова в урлах тегов
- [x] дублируются теги, если отредактировать, сохранить и не закрыть страницу редактирования
- [x] не удобно закрытие по кнопке сохранить

**Товары**

- [ ] поле фильтры по размеру

**Comment by marymal** [comment]
http://admin.presswall.springhead.su

**Comment by evgeniysolodkov** [comment]
@marymal Возможно, надо будет сделать две кнопки - Сохранить и Сохранить и закрыть
